version: '3.8'

services:
  frontend:
    build:
      context: ./devops-bootcamp-todolist-frontend
      dockerfile: Dockerfile
    container_name: todolist-frontend
    env_file:
      - .env
    ports:
      - "3000:3000"
